import { AlertCircle, BookOpen, Github } from "lucide-react";

export function Footer() {
  return (
    <footer className="relative mt-auto border-t border-border/60 bg-gradient-to-b from-surface/60 to-surface-secondary/80 backdrop-blur supports-[backdrop-filter]:bg-surface/40">
      {/* Accent gradient bar */}
      <div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-brand-primary/0 via-brand-primary/70 to-brand-primary/0" />
      <div className="mx-auto w-full max-w-7xl px-4 sm:px-6 lg:px-8 py-6">
        <div className="flex flex-col gap-4">
          {/* Disclaimer */}
          <div className="flex items-start gap-2 rounded-lg border border-border/40 bg-surface-secondary/30 p-3">
            <AlertCircle
              className="h-3.5 w-3.5 text-text-tertiary/70 mt-0.5 flex-shrink-0"
              aria-hidden
            />
            <div className="space-y-1 text-sm text-text-tertiary/90 leading-relaxed">
              <p>
                <span className="font-semibold text-text-secondary">
                  Disclaimer:
                </span>{" "}
                Sentiment predictions are generated by a machine learning model
                and may not reflect accurate emotional states. This is an
                educational demonstration—not intended for research or
                production use.
              </p>
            </div>
          </div>
          {/* Main content */}
          <div className="flex flex-col sm:flex-row items-center justify-between gap-4">
            {/* Left: Project info */}
            <div className="flex flex-col sm:flex-row items-center gap-3 text-sm">
              <div className="flex items-center gap-2">
                <div
                  className="h-7 w-7 rounded bg-gradient-to-tr from-brand-primary to-brand-primary/60 shadow-sm flex items-center justify-center"
                  aria-hidden
                >
                  <BookOpen className="h-4 w-4 text-white" />
                </div>
                <span className="font-medium text-text-secondary">
                  Datacenter Scale Computing Project 2025
                </span>
              </div>
              <span className="hidden sm:inline text-text-tertiary/50">•</span>
              <span className="text-text-tertiary">Richard Roberson</span>
            </div>

            {/* Right: Links */}
            <div className="flex items-center gap-3">
              <a
                href="https://github.com/richardr1126/final-project"
                target="_blank"
                rel="noreferrer"
                className="inline-flex items-center gap-1.5 rounded-md border border-border bg-surface-secondary/70 px-3 py-1.5 text-xs font-medium text-text-secondary shadow-sm transition hover:bg-surface-secondary hover:text-text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-primary/60"
              >
                <Github className="h-3.5 w-3.5" aria-hidden />
                <span>View Source</span>
              </a>
            </div>
          </div>
        </div>
      </div>
    </footer>
  );
}
